### Slide 3: Lambda Function

In [ ]:
# Named function
def square(x):
    return x**2

square(5)

25

In [ ]:
# Equivalent lambda
square_lambda = lambda x: x**2
a = square_lambda(5)
a

# Note square_lambda is just a variable to which lambda is assigned but there is no function named as square_lambda here

25

In [ ]:
# Lambda can be used directly without being assigned to a variable
y=10
(lambda x,y: x**2+y**2)(5,10)

125

In [ ]:
# Filtering a list based on a condition within a lambda function
nums = [3, 5, 8, 10]
list(filter(lambda x: x % 2 == 0, nums))

[8, 10]

In [ ]:
# Map each element in list to its square using lambda function within a map function
list(map(lambda x: x**2, nums))

[9, 25, 64, 100]

In [ ]:
# To check if a number is even or odd
check_even_odd = lambda x: "Even" if x % 2 == 0 else "Odd"

print(check_even_odd(4))
print(check_even_odd(7))

Even
Odd

In [ ]:
# Looping over a list and apply square function over all numbers
nums = [-3, -1, 0, 2, 5, -7]
Eo = [(lambda x: "Even" if x%2==0 else "Odd")(x) for x in nums]
print(Eo)

['Odd', 'Odd', 'Even', 'Even', 'Odd', 'Odd']

## Pandas

In [ ]:
import pandas as pd
import numpy as np

### Slide 5 : Pandas Building Blocks

In [ ]:
# Creating a Series
s = pd.Series([3.5, 4.5, 5.0])
print(s)

0    3.5
1    4.5
2    5.0
dtype: float64

In [ ]:
# Creating a DataFrame
df = pd.DataFrame({
    "Name": ["Anu", "Ben", "Cathy"],
    "Age": [23, 25, 22],
    "Score": [91, 88, 95]
})
df

    Name  Age  Score
0    Anu   23     91
1    Ben   25     88
2  Cathy   22     95

In [ ]:
s.info()
df.info()

<class 'pandas.core.series.Series'>
RangeIndex: 3 entries, 0 to 2
Series name: None
Non-Null Count  Dtype
--------------  -----
3 non-null      float64
dtypes: float64(1)
memory usage: 156.0 bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Score   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [ ]:
df1 = pd.DataFrame({"Marks": [85, 90, 78]}, index=["A1", "A2", "A3"])
df1.index = df1["Marks"]
df1

       Marks
Marks
85        85
90        90
78        78

In [ ]:
# Every column in a Dataframe can be taken out as a Series object

name1 = df.Name
name2 = df["Name"]

In [ ]:
name2

0      Anu
1      Ben
2    Cathy
Name: Name, dtype: object

In [ ]:
name1.info()

<class 'pandas.core.series.Series'>
RangeIndex: 3 entries, 0 to 2
Series name: Name
Non-Null Count  Dtype
--------------  -----
3 non-null      object
dtypes: object(1)
memory usage: 156.0+ bytes

### Slide 6 : Selection using loc

In [ ]:
df = pd.DataFrame({
    "Name": ["Asha", "Bala", "Chetan", "Divya"],
    "Marks": [85, 90, 78, 92],
    "City": ["Chennai", "Pune", "Delhi", "Vizag"]
}, index=["s1", "s2", "s3", "s4"])
df

      Name  Marks     City
s1    Asha     85  Chennai
s2    Bala     90     Pune
s3  Chetan     78    Delhi
s4   Divya     92    Vizag

In [ ]:
# Access single cell
df.loc["s2", "Marks"]

np.int64(90)

In [ ]:
# Access multiple rows & columns
df.loc[["s1","s2"], ["Name","Marks"]]

    Name  Marks
s1  Asha     85
s2  Bala     90

In [ ]:
# Conditional selection
df.loc[(df["Marks"] > 80) & (df["City"]=="Chennai"), ["Name", "City"]]

    Name     City
s1  Asha  Chennai

In [ ]:
# Select students  who scored above 60 using a lambda function
df.loc[lambda x: (x["Marks"] > 60) & (x["City"]=="Chennai"), ["Name", "Marks"]]

    Name  Marks
s1  Asha     85

### Slide 7 : Selection using iloc

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Asha", "Bala", "Chetan", "Divya"],
    "Marks": [85, 90, 78, 92],
    "City": ["Chennai", "Pune", "Delhi", "Vizag"]
}, index=["s1", "s2", "s3", "s4"])
df

      Name  Marks     City
s1    Asha     85  Chennai
s2    Bala     90     Pune
s3  Chetan     78    Delhi
s4   Divya     92    Vizag

In [ ]:
# Access specific cell
df.iloc[1, 1]

np.int64(90)

In [ ]:
# Range selection
df.iloc[0:2, 0:2]

    Name  Marks
s1  Asha     85
s2  Bala     90

In [ ]:
# Negative indexing works too
df.iloc[::-2,::-2]

     City   Name
s4  Vizag  Divya
s2   Pune   Bala

### Slide 8: Filtering using query function

In [ ]:
df = pd.DataFrame({
    "Name": ["Asha", "Bala", "Chetan", "Divya"],
    "Marks": [85, 90, 78, 92],
    "City": ["Chennai", "Pune", "Delhi", "Vizag"]
}, index=["s1", "s2", "s3", "s4"])
df

      Name  Marks     City
s1    Asha     85  Chennai
s2    Bala     90     Pune
s3  Chetan     78    Delhi
s4   Divya     92    Vizag

In [ ]:
# Conditional selection using .query
df.query("Marks > 80")[["Name", "City"]]

     Name     City
s1   Asha  Chennai
s2   Bala     Pune
s4  Divya    Vizag

In [ ]:
# NEW TO ME: @cutoff - external variable, and/or instead of &/| in query
# Conditional selectiong using query based on an external variable
cutoff = "Chennai"
df.query("City==@cutoff and Marks > 80")[["Name", "Marks"]]

    Name  Marks
s1  Asha     85

### Slide 10/11: Copies and Views of Dataframes

In [ ]:
df = pd.DataFrame({
    "Department": ["Sales", "Sales", "HR", "HR", "IT", "IT"],
    "Employee": ["Asha", "Bala", "Chetan", "Divya", "Esha", "Farhan"],
    "Salary": [50, 55, 40, 42, 60, 62]
})

df1 = df["Department"]
# NEW TO ME
df1._is_view

True

In [ ]:
df1 = df["Department"].copy()
df1._is_view

False

### Slide 12: Inplace Operations in Dataframes

In [ ]:
df = pd.DataFrame({
    "Department": ["Sales", "Sales", "HR", "HR", "IT", "IT"],
    "Employee": ["Asha", "Bala", "Chetan", None, "Esha", "Farhan"],
    "Salary": [50, 55, 40, 42, 60, np.nan]
})
df = df.dropna()
df

  Department Employee  Salary
0      Sales     Asha    50.0
1      Sales     Bala    55.0
2         HR   Chetan    40.0
4         IT     Esha    60.0

### Slide 14 : Updating values in DataFrame

In [ ]:
df = pd.DataFrame({
    "Name": ["Asha", "Bala", "Chetan", "Divya", "Jay"],
    "Marks": [85, 40, 78, 92, 53],
    "City": ["Chennai", "Pune", "Delhi", "Vizag", "Mumbai"]
})

In [ ]:
# Set a single cell (label-based)
df.loc[1, "Marks"] = 95 # 1 here refers to index and not position though both are same
df

     Name  Marks     City
0    Asha     85  Chennai
1    Bala     95     Pune
2  Chetan     78    Delhi
3   Divya     92    Vizag
4     Jay     53   Mumbai

In [ ]:
# NEW TO ME: Set a single cell (label-based)
df.at[1, "Marks"] = 90 # Faster than .loc for scalar assignment
df

     Name  Marks     City
0    Asha     85  Chennai
1    Bala     90     Pune
2  Chetan     78    Delhi
3   Divya     92    Vizag
4     Jay     53   Mumbai

In [ ]:
# Set via position
df.iloc[0, 1] = 88
df

     Name  Marks     City
0    Asha     88  Chennai
1    Bala     90     Pune
2  Chetan     78    Delhi
3   Divya     92    Vizag
4     Jay     53   Mumbai

In [ ]:
# NEW TO ME: Set via position
df.iat[0, 1] = 90 # Faster than .iloc for scalar assignment
df

     Name  Marks     City
0    Asha     90  Chennai
1    Bala     90     Pune
2  Chetan     78    Delhi
3   Divya     92    Vizag
4     Jay     53   Mumbai

In [ ]:
# Set multiple cells via a condition and broadcasting
df.loc[df["City"] == "Delhi", "Marks"] = 80
df

     Name  Marks     City
0    Asha     88  Chennai
1    Bala     95     Pune
2  Chetan     80    Delhi
3   Divya     92    Vizag
4     Jay     53   Mumbai

In [ ]:
# Set entire column via broadcasting
df["Passed"] = (df["Marks"] >= 80)
df

     Name  Marks     City  Passed
0    Asha     88  Chennai    True
1    Bala     95     Pune    True
2  Chetan     80    Delhi    True
3   Divya     92    Vizag    True
4     Jay     53   Mumbai   False

In [ ]:
# Setting conditionally via a lambda function: Increase marks by 5 for those below 60
# Vectorised and Broadcasted and inplace modification
df.loc[lambda x: x["Marks"] < 60, "Marks"] += 5
df

     Name  Marks     City
0    Asha     90  Chennai
1    Bala     90     Pune
2  Chetan     78    Delhi
3   Divya     92    Vizag
4     Jay     58   Mumbai

In [ ]:
# NEW TO ME: Conditional setting via .where()
# .where() keeps values where a condition is True, replaces values where the condition is False and returns a new object
df1 = df.copy()
df1['City'].where(df1['Marks'] == 90, inplace=True) # NaN is the default replacement
df1

/tmp/ipython-input-590743660.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['City'].where(df1['Marks'] == 90, inplace=True) # NaN is the default replacement

     Name  Marks     City
0    Asha     90  Chennai
1    Bala     90     Pune
2  Chetan     78      NaN
3   Divya     92      NaN
4     Jay     58      NaN

In [ ]:
# Value substitution using replace
# Can also be used with regex
df = pd.DataFrame({
    "Name": ["Asha", "Bala", "Chetan", "Divya", "Jay"],
    "Marks": [85, 40, 78, 92, 53],
    "City": ["Chn", "Pune", "Delhi", "Hyd", "Mumbai"]
})
df['City'] = df['City'].replace({'': 'Hyderabad', 'Chn': 'Chennai'})
df

     Name  Marks       City
0    Asha     85    Chennai
1    Bala     40       Pune
2  Chetan     78      Delhi
3   Divya     92  Hyderabad
4     Jay     53     Mumbai

### Slide 16: Setting With Copy Warning

In [ ]:
df = pd.DataFrame({
    "A": [3, 6, 8, 2, 9],
    "B": [10, 20, 30, 40, 50]
})
df

   A   B
0  3  10
1  6  20
2  8  30
3  2  40
4  9  50

In [ ]:
df[df["A"]>5]["B"] = 0
df

/tmp/ipython-input-694041979.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df["A"]>5]["B"] = 0

   A   B
0  3  10
1  6  20
2  8  30
3  2  40
4  9  50

### Slide 17: _Grouping_ Operations

In [ ]:
df = pd.DataFrame({
    "Department": ["Sales", "Sales", "HR", "HR", "IT", "IT"],
    "Employee": ["Asha", "Bala", "Chetan", "Divya", "Esha", "Farhan"],
    "Salary": [50000, 55000, 40000, 42000, 60000, 62000],
    "Experience": [2, 4, 3, 5, 6, 8]
})
print(df)
grouped = df.groupby("Department")
grouped  # GroupBy object and not a dataframe

  Department Employee  Salary  Experience
0      Sales     Asha   50000           2
1      Sales     Bala   55000           4
2         HR   Chetan   40000           3
3         HR    Divya   42000           5
4         IT     Esha   60000           6
5         IT   Farhan   62000           8

In [ ]:
grouped.groups

{'HR': [2, 3], 'IT': [4, 5], 'Sales': [0, 1]}

In [ ]:
# NEW TO ME
grouped.get_group("HR")

  Department Employee  Salary  Experience
2         HR   Chetan   40000           3
3         HR    Divya   42000           5

### Slide 17: Aggregations after Grouping

In [ ]:
# Simple aggregation resulting in creation of a new series object
df1 = df.groupby("Department")["Salary"].mean()
df1

Department
HR       41000.0
IT       61000.0
Sales    52500.0
Name: Salary, dtype: float64

In [ ]:
# Multiple aggregations
df.groupby("Department")["Salary"].agg(["mean", "max", "min"])

               mean    max    min
Department
HR          41000.0  42000  40000
IT          61000.0  62000  60000
Sales       52500.0  55000  50000

In [ ]:
# Different functions for different columns
df.groupby("Department").agg({
    "Salary": ["mean", "max"],
    "Experience": "median"
})

             Salary        Experience
               mean    max     median
Department
HR          41000.0  42000        4.0
IT          61000.0  62000        7.0
Sales       52500.0  55000        3.0

In [ ]:
# Group by and Aggregate by more than one column
df.groupby(["Department", "Experience"])["Salary"].mean()

Department  Experience
HR          3             40000.0
            5             42000.0
IT          6             60000.0
            8             62000.0
Sales       2             50000.0
            4             55000.0
Name: Salary, dtype: float64

In [ ]:
# Custom function based aggregation
def range(x):
    return x.max() - x.min()

df.groupby("Department")["Salary"].agg(["mean", range])

               mean  range
Department
HR          41000.0   2000
IT          61000.0   2000
Sales       52500.0   5000

### Slide 18: Transform and Filter after Grouping

In [ ]:
df = pd.DataFrame({
    "Department": ["Sales", "Sales", "HR", "HR", "IT", "IT"],
    "Employee": ["Asha", "Bala", "Chetan", "Divya", "Esha", "Farhan"],
    "Salary": [50, 55, 40, 42, 60, 62]
})

# NEW TO ME
df["DeptAvgSalary"] = df.groupby("Department")["Salary"].transform("mean") # Multiple transformations are not allowed at once in recent versions of pandas
df

  Department Employee  Salary  DeptAvgSalary
0      Sales     Asha      50           52.5
1      Sales     Bala      55           52.5
2         HR   Chetan      40           41.0
3         HR    Divya      42           41.0
4         IT     Esha      60           61.0
5         IT   Farhan      62           61.0

In [ ]:
# Keep only departments where average salary > 50
df_filtered = df.groupby("Department").filter(lambda x: x["Salary"].mean() > 50)
df_filtered

  Department Employee  Salary  DeptAvgSalary
0      Sales     Asha      50           52.5
1      Sales     Bala      55           52.5
4         IT     Esha      60           61.0
5         IT   Farhan      62           61.0

In [ ]:
# Filter by presence of a condition
# Keeps any department that has at least one employee earning > 60
df.groupby("Department").filter(lambda g: (g["Salary"] > 60).any())

  Department Employee  Salary  DeptAvgSalary
4         IT     Esha      60           61.0
5         IT   Farhan      62           61.0

In [ ]:
# Filter by all condition
# Keep only departments where all salaries are above 45
df.groupby("Department").filter(lambda g: (g["Salary"] > 52).all())

  Department Employee  Salary  DeptAvgSalary
4         IT     Esha      60           61.0
5         IT   Farhan      62           61.0

### Slide 20 : Categorical Values in Pandas

In [ ]:
df = pd.DataFrame({
    "Region": ["East", "West", "North", "East", "West"]
})
print(df["Region"].dtype)
df["Region"] = df["Region"].astype("category") # Setting the data type of the column to "category"
print(df["Region"].dtype)

object
category

In [ ]:
df["Region"].cat.categories  # Returns the list of categories used in a column

Index(['East', 'North', 'West'], dtype='object')

In [ ]:
# Rename categories
df["Region"] = df["Region"].cat.rename_categories({"East": "E", "West": "W", "North": "N"})

# Reorder (for ordered comparisons)
df["Region"] = df["Region"].cat.reorder_categories(["N", "E", "W"], ordered=True)

# Add Category
df["Region"] = df["Region"].cat.add_categories(["S"])

In [ ]:
df["Region"].cat.categories

Index(['N', 'E', 'W', 'S'], dtype='object')

### Slide 21: Handling Missing Values

In [ ]:
df = pd.DataFrame({
    "Name": ["Asha", "Bala", "Jay", "Divya"],
    "Marks": [85, np.nan, 78, 90],
    "City": ["Chennai", None, "Delhi", "Vizag"]
})

In [ ]:
# Returns a dataframe of boolean values showing True where value is missing
df.isna()

    Name  Marks   City
0  False  False  False
1  False   True   True
2  False  False  False
3  False  False  False

In [ ]:
# Dropping rows with missing values
df1 = df.dropna()
df1

    Name  Marks     City
0   Asha   85.0  Chennai
2    Jay   78.0    Delhi
3  Divya   90.0    Vizag

In [ ]:
# Dropping columns with missing values
# axis = 0 (rows) by default
df1 = df.dropna(axis=1)
df1

    Name
0   Asha
1   Bala
2    Jay
3  Divya

In [ ]:
# Filling or imputing missing values
df["Marks"] = df["Marks"].fillna(0)
df

    Name  Marks     City
0   Asha   85.0  Chennai
1   Bala    0.0     None
2    Jay   78.0    Delhi
3  Divya   90.0    Vizag

In [ ]:
# Filling or imputing missing values
df["Marks"] = df["Marks"].fillna(80)
df

    Name  Marks     City
0   Asha   85.0  Chennai
1   Bala   80.0     None
2    Jay   78.0    Delhi
3  Divya   90.0    Vizag

### Slide 23/24: File Read/Write Operations in Pandas

In [ ]:
df = pd.read_csv("sample_data/california_housing_train.csv")
df.head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
5,-114.58,33.63,29.0,1387.0,236.0,671.0,239.0,3.3438,74000.0
6,-114.58,33.61,25.0,2907.0,680.0,1841.0,633.0,2.6768,82400.0
7,-114.59,34.83,41.0,812.0,168.0,375.0,158.0,1.7083,48500.0
8,-114.59,33.61,34.0,4789.0,1175.0,3134.0,1056.0,2.1782,58400.0
9,-114.60,34.83,46.0,1497.0,309.0,787.0,271.0,2.1908,48100.0

In [ ]:
len(df)

17000

In [ ]:
# Reading only some rows and columns from the file
df1 = pd.read_csv("sample_data/california_housing_train.csv", nrows=100, usecols=["longitude", "latitude"])
df1.head()
# len(df1)

   longitude  latitude
0    -114.31     34.19
1    -114.47     34.40
2    -114.56     33.69
3    -114.57     33.64
4    -114.57     33.57

In [ ]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

In [ ]:
# Changing data type of a column
df["total_rooms"] = df["total_rooms"].astype("int")
df["total_rooms"].dtype

dtype('int64')

In [ ]:
# Writing to a csv file
df1.to_csv("data.csv")

In [ ]:
# Writing specific columns to a target sheet in excel file
df.to_excel("data.xlsx", sheet_name="Summary", columns=['total_rooms','latitude'])

In [ ]:
# Writing specific columns to multiple target sheets in a excel file
with pd.ExcelWriter("data_housing.xlsx") as writer:
    df.to_excel(writer, sheet_name="total_rooms", columns=['total_rooms'])
    df.to_excel(writer, sheet_name="latitude", columns=['latitude'])